version: '3'

services:
  app:
    container_name: nette-project-app
    image: sunfoxcz/php:7.4-fpm
    working_dir: /app
    environment:
      - NETTE_DEVEL=1
    volumes:
      - .:/app
      - ./docker/php/pool-www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    links:
      - mysql

  nginx:
    container_name: nette-project-nginx
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./docker/nginx/dev.crt:/etc/nginx/nginx.crt
      - ./docker/nginx/dev.key:/etc/nginx/nginx.key
    links:
      - app

  mysql:
    container_name: nette-project-db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=xxx
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf

  adminer:
    container_name: nette-project-adminer
    image: pkristian/adminer
    ports:
      - 8080:8080
    links:
      - mysql:db

volumes:
  mysql-data:
